### ISSUE TITLE
The URL from which CMake is downloaded seems to be broken.

### ISSUE THREAD

**Issue by adamnemecek** [JuliaPackaging/CMake.jl#12]
CMake.jl tried to download cmake from URL https://cmake.org/files/v3.12/cmake-3.12.3-Darwin-x86_64.tar.gz. For some reason this URL redirects to cmake.org so the downloaded file "cmake-3.12.3-Darwin-x86_64.tar.gz" is actually an HTML file in disguise. 

The correct URL is https://github.com/Kitware/CMake/releases/download/v3.13.2/cmake-3.13.2-Darwin-x86_64.tar.gz

As a result, I get the error
ERROR: LoadError: failed process: Process(`tar xzf /Users/adamnemecek/Code/hypersphere/ngrid.io/ngrid.io/julia_depot/dev/CMake/deps/downloads/cmake-3.12.3-Darwin-x86_64.tar.gz --directory=/Users/adamnemecek/Code/hypersphere/ngrid.io/ngrid.io/julia_depot/dev/CMake/deps/downloads`, ProcessExited(1)) [1]

**Comment by WibbletheDuck** [comment]
This appears to be due to Kitware [moving to a new office](https://blog.kitware.com/important-update-for-online-resources-while-we-move/)—they kept the latest binary versions up, but not older.  Rather agree that if they're hosting files on local servers (what year is it?), it would probably make more sense to download from the git mirror...

**Comment by adamnemecek** [comment]
I read the site like 2 minutes after opening the issue haha. I'll submit a pull request but I'm having a hard time testing this.

**Comment by stevengj** [comment]
Closed by #13, thanks
